/*
 *
 * Criado em: 10/07/2021
 *
 * CREATE DATABASE mybookmark;
 *
 * source /home/hb/git/MyBookMark/MyBookMark/MySQL/mybookmark.sql
 *
 */

/*
 * ALTER TABLE Chronometer MODIFY COLUMN dateOf DATETIME NOT NULL; 
 * 
 * ALTER TABLE Countdown MODIFY COLUMN dateOf DATETIME NOT NULL; 
 * 
 */

/*
 * ALTER TABLE Divs ADD COLUMN orderOf BIGINT UNSIGNED NOT NULL DEFAULT 1000; 
 * 
 * ALTER TABLE Categories ADD COLUMN orderOf BIGINT UNSIGNED NOT NULL DEFAULT 1000;
 *  
 * ALTER TABLE Links ADD COLUMN orderOf BIGINT UNSIGNED NOT NULL DEFAULT 1000;
 * 
 * ALTER TABLE MonthlyReminder ADD COLUMN orderOf BIGINT UNSIGNED NOT NULL DEFAULT 1000; 
 * 
 * ALTER TABLE AnnualReminder ADD COLUMN orderOf BIGINT UNSIGNED NOT NULL DEFAULT 1000; 
 * 
 * ALTER TABLE Countdown ADD COLUMN orderOf BIGINT UNSIGNED NOT NULL DEFAULT 1000; 
 * 
 * ALTER TABLE Chronometer ADD COLUMN orderOf BIGINT UNSIGNED NOT NULL DEFAULT 1000; 
 * 
 * ALTER TABLE Settings ADD COLUMN orderOf BIGINT UNSIGNED NOT NULL DEFAULT 1000;  
 * 
 */

/*
 * UPDATE Divs SET orderOf = id; 
 * 
 * UPDATE Categories SET orderOf = id; 
 *  
 * UPDATE Links SET orderOf = id; 
 * 
 * UPDATE MonthlyReminder SET orderOf = id; 
 * 
 * UPDATE AnnualReminder SET orderOf = id; 
 * 
 * UPDATE Countdown SET orderOf = id; 
 * 
 * UPDATE Chronometer SET orderOf = id;  
 * 
 * UPDATE Settings SET orderOf = id;  
 * 
 */

USE mybookmark;

CREATE TABLE IF NOT EXISTS Divs (
    id SERIAL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL DEFAULT '',
    position ENUM ('LEFT', 'CENTER', 'RIGHT', 'BOTTOM') NOT NULL,
	lastUpdatedOn TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	createdOn TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id, name)
);

CREATE TABLE IF NOT EXISTS Categories (
    id SERIAL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL DEFAULT '',
	divs BIGINT UNSIGNED NOT NULL REFERENCES Divs(id),
	lastUpdatedOn TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	createdOn TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS Links (
	id SERIAL AUTO_INCREMENT,
	name VARCHAR(255) NOT NULL,
	description VARCHAR(255) NOT NULL DEFAULT '',
    link TEXT NOT NULL,
    category BIGINT UNSIGNED NOT NULL REFERENCES categories(id),
	lastUpdatedOn TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	createdOn TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS Chronometer (
	id SERIAL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL DEFAULT '',
    dateOf TIMESTAMP NOT NULL,
    category BIGINT UNSIGNED NOT NULL REFERENCES categories(id),
	lastUpdatedOn TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	createdOn TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS Countdown (
	id SERIAL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL DEFAULT '',
    dateOf TIMESTAMP NOT NULL,
    category BIGINT UNSIGNED NOT NULL REFERENCES categories(id),
	lastUpdatedOn TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	createdOn TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS MonthlyReminder (
	id SERIAL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL DEFAULT '',
    day BIGINT UNSIGNED NOT NULL,
    category BIGINT UNSIGNED NOT NULL REFERENCES categories(id),
    daysBefore BIGINT UNSIGNED NOT NULL,
    daysAfter BIGINT UNSIGNED NOT NULL,
	lastUpdatedOn TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	createdOn TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS AnnualReminder (
    id SERIAL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL DEFAULT '',
    day BIGINT UNSIGNED NOT NULL,
    month BIGINT UNSIGNED NOT NULL,
    category BIGINT UNSIGNED NOT NULL REFERENCES categories(id),
    daysBefore BIGINT UNSIGNED NOT NULL,
    daysAfter BIGINT UNSIGNED NOT NULL,
	lastUpdatedOn TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	createdOn TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS Settings (
  id SERIAL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  description VARCHAR(255) NOT NULL DEFAULT '',
  theme ENUM ('LIGHT', 'DARK') NOT NULL,
  lastUpdatedOn TIMESTAMP DEFAULT (CURRENT_TIMESTAMP) ON UPDATE CURRENT_TIMESTAMP,
  createdOn TIMESTAMP DEFAULT (CURRENT_TIMESTAMP),
  PRIMARY KEY (id)
);

INSERT INTO Divs (name, position) VALUES ('Div LEFT', 'LEFT');
INSERT INTO Divs (name, position) VALUES ('Div CENTER', 'CENTER');
INSERT INTO Divs (name, position) VALUES ('Div RIGHT', 'RIGHT');

INSERT INTO Settings (name, description, theme) VALUES ('Default', 'Default Settings', 'DARK');

